name: MediQ
description: "Antibiotics Usage Analysis System For Karapitiya National Hospital. Collaboration with Karapitiya National Hospital"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  fl_chart: ^0.66.0

  flutter_typeahead: ^4.0.0

  csv: ^5.0.1
  share_plus: ^7.2.0
  path_provider: ^2.1.1

  font_awesome_flutter: ^10.7.0
  fluentui_system_icons: ^1.1.232

  # FIXED → Correct version from pub.dev
  material_symbols_icons: ^4.2874.0

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  

  # Firebase Packages
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7

  # Image handling
  image_picker: ^1.2.0
  #image_cropper: ^5.0.1
  flutter_image_compress: ^2.3.0

  # HTTP for Cloudinary upload
  http: ^1.1.1

  # URL Launcher
  url_launcher: ^6.2.0

  # Utilities
  path: ^1.9.1
  fluttertoast: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo2.png"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/logo/logo.png
    - assets/logo/logo2.png
    
    - assets/developer/developer_photo.png

    - assets/accounts/admin-default.jpg
    - assets/accounts/pharmizist-default.jpg

    - assets/antibiotics/manage_antibiotic.jpg
    - assets/antibiotics/add_antibiotic.jpg

    - assets/wards/add-ward.png
    - assets/wards/manage-ward.png

    - assets/stores/main_store.jpg
    - assets/stores/return_store.jpg

    - assets/usages/release_details.png
    - assets/usages/return_details.jpg

    - assets/analyst/antibiotic-usage.jpg
    - assets/analyst/ward-usage.jpg
    - assets/analyst/all-usage.jpg

    - assets/analyst/cards/antibiotics-overviews/releases-all.jpg
    - assets/analyst/cards/antibiotics-overviews/returns-all.jpg
    - assets/analyst/cards/antibiotics-overviews/releases.jpg
    - assets/analyst/cards/antibiotics-overviews/returns.png

    - assets/analyst/cards/ward-wise-overviews/releases-all.jpg
    - assets/analyst/cards/ward-wise-overviews/returns-all.jpg
    - assets/analyst/cards/ward-wise-overviews/releases.jpg
    - assets/analyst/cards/ward-wise-overviews/returns.jpg
