// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp2Pgje7sN7HRh7W18UblxLJhYzIktGhA',
    appId: '1:99050504513:web:938a1d698a026ea50f21c0',
    messagingSenderId: '99050504513',
    projectId: 'mediqapp-c6fe8',
    authDomain: 'mediqapp-c6fe8.firebaseapp.com',
    storageBucket: 'mediqapp-c6fe8.firebasestorage.app',
    measurementId: 'G-KT0PXHXV1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBVP_LJ1xzHHVvAQbR-JOzYrO8doERYnU',
    appId: '1:99050504513:android:51b1ab54af94f3850f21c0',
    messagingSenderId: '99050504513',
    projectId: 'mediqapp-c6fe8',
    storageBucket: 'mediqapp-c6fe8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDLil_pXRzMr3SJZKN9uh29HylqUwg9QI',
    appId: '1:99050504513:ios:550a69be84936b250f21c0',
    messagingSenderId: '99050504513',
    projectId: 'mediqapp-c6fe8',
    storageBucket: 'mediqapp-c6fe8.firebasestorage.app',
    iosBundleId: 'com.example.mediq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDLil_pXRzMr3SJZKN9uh29HylqUwg9QI',
    appId: '1:99050504513:ios:550a69be84936b250f21c0',
    messagingSenderId: '99050504513',
    projectId: 'mediqapp-c6fe8',
    storageBucket: 'mediqapp-c6fe8.firebasestorage.app',
    iosBundleId: 'com.example.mediq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp2Pgje7sN7HRh7W18UblxLJhYzIktGhA',
    appId: '1:99050504513:web:7df3d0c83b790b710f21c0',
    messagingSenderId: '99050504513',
    projectId: 'mediqapp-c6fe8',
    authDomain: 'mediqapp-c6fe8.firebaseapp.com',
    storageBucket: 'mediqapp-c6fe8.firebasestorage.app',
    measurementId: 'G-H7ZDLH8W9T',
  );

}